### ISSUE TITLE
GitHub Action doesn't trigger on tag push

### ISSUE THREAD

**Issue by toolmantim** [toolmantim/release-drafter#196]
Pushing tags doesn't trigger a new draft release when a new tag goes out, as it thinks it's a branch and ignores it ( https://github.com/toolmantim/release-drafter/runs/113476390). It should always run for tag pushes, and only filter branches for code pushes to `refs/head*`

**Comment by toolmantim** [comment]
I don't think this is a blocker for release. Closing for now.

**Comment by casz** [comment]
I'd reopen it, I see it as an issue if you do not trigger on both tags and pushes 😓 Especially if your tag push comes several hours after your git push, I'd like for the draft to at least update the `untagged-SHA`

This could also solve #203 and #204 since it should only care to find a tag that matches the tag template to set the proper release draft target.
