### ISSUE TITLE
Release Author

### ISSUE THREAD

**Issue by hunterjm** [toolmantim/release-drafter#260]
It looks like in your latest releases, the author is attributed to you.

![image](https://user-images.githubusercontent.com/747670/61332932-86162300-a7f3-11e9-9c83-2c291e55ff04.png)

Previously, it was either release-drafter and more recently github-actions:

![image](https://user-images.githubusercontent.com/747670/61332979-a1812e00-a7f3-11e9-9cc6-d2f95902f806.png)

I've switched from the bot to using github-actions thinking this would help fix the author, but I'm showing github-actions still.  How did you get the draft to publish under your name?

This is required due to my CI having authorization for building releases for tags based on the author of the tag (which was previously the bot and would fail).

Thanks in advance!

**Comment by toolmantim** [comment]
I’m afraid that release was cut manually, copy and pasting the existing content, because the GitHub UI was throwing a 500 at the time when I tried editing the draft release that Release Drafter had created.

There’s no GitHub API that I know of that let’s you set the release authorship correctly, otherwise we’d love to use it.

**Comment by hunterjm** [comment]
Thanks. That’s the process we are using currently. Closing the ticket.
